export const routePaths = {
  landing: '/',
  login: '/login',
  storeSelection: '/store-selection',
  initialSetup: '/initial-setup',
  systemStart: '/system-start',
  dayClosed: '/day-closed',
  dashboard: '/dashboard',
  inventory: '/inventory',
  ocrInbound: '/ocr-inbound',
  orderGuide: '/order-guide',
  closing: '/closing',
  closingOrderGuideDetail: '/closing/order-guide-detail',
  notifications: '/notifications',
  storeSettings: '/store-settings',
  storeSettingsMenus: '/store-settings/menus',
  storeSettingsMenuBoard: '/store-settings/menu-board',
  storeSettingsRecipes: '/store-settings/recipes',
  storeSettingsIngredients: '/store-settings/ingredients',
  settings: '/settings',
  support: '/support',
  customerOrder: '/menu/:shopId',
  authCallback: '/auth/callback',
  notFound: '*',
} as const;
