export const routePaths = {
  landing: '/',
  login: '/login',
  storeSelection: '/store-selection',
  initialSetup: '/initial-setup',
  dashboard: '/dashboard',
  inventoryCurrent: '/inventory/current',
  inventoryDepleted: '/inventory/depleted',
  orderGuide: '/order-guide',
  priceAnalysis: '/ingredient-price-analysis',
  notifications: '/notifications',
  settings: '/settings',
  settingsMenus: '/settings/menus',
  settingsRecipes: '/settings/recipes',
  settingsIngredients: '/settings/ingredients',
  account: '/account',
  support: '/support',
  notFound: '*',
} as const;
