export const routePaths = {
  landing: '/',
  login: '/login',
  storeSelection: '/store-selection',
  initialSetup: '/initial-setup',
  dashboard: '/dashboard',
  inventory: '/inventory',
  ocrInbound: '/ocr-inbound',
  orderGuide: '/order-guide',
  notifications: '/notifications',
  storeSettings: '/store-settings',
  storeSettingsMenus: '/store-settings/menus',
  storeSettingsRecipes: '/store-settings/recipes',
  storeSettingsIngredients: '/store-settings/ingredients',
  settings: '/settings',
  support: '/support',
  customerOrder: '/menu/:shopId',
  notFound: '*',
} as const;
